### ISSUE TITLE
UnzipProgress 中的流未关闭

### ISSUE THREAD

**Issue by jinlu** [dpull/AssetBundlePatch#2]
学习您的代码很长时间了，非常感谢您的分享

有个小问题请教您

发现UnzipProgress类中SourceArchiveFile，ZipStream 这2个流没有close，可能在别的地方处理了，我没有看到，还请指教一下。

**Comment by dpull** [comment]
OK 多谢 我补上

**Comment by jinlu** [comment]
加个qq吧，交个朋友(42420026)
